# Generated by Django 4.1.7 on 2023-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('MA_HOC_SINH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HO_TEN', models.CharField(max_length=100)),
                ('NGAY_SINH', models.DateField()),
                ('GIOI_TINH', models.BooleanField()),
                ('DIA_CHI', models.CharField(max_length=200)),
            ],
        ),
    ]
